package gui;

import bl.Obstacle;
import bl.Player;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vizug
 */
public class MainGUI extends javax.swing.JFrame implements Runnable {

    private Obstacle obstacle = new Obstacle(2, 1);
    private Player player = new Player(50, 50);

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        this.setVisible(true);
        this.setFocusable(false);
        panelGame.setFocusable(true);
        //this.run();

        Thread t = new Thread(this);
        t.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGame = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meGame = new javax.swing.JMenu();
        miCreateUser = new javax.swing.JMenuItem();
        miSelectDifficulty = new javax.swing.JMenuItem();
        miStartGame = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelGameKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelGameLayout = new javax.swing.GroupLayout(panelGame);
        panelGame.setLayout(panelGameLayout);
        panelGameLayout.setHorizontalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelGameLayout.setVerticalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        meGame.setText("Game");

        miCreateUser.setText("Create User");
        meGame.add(miCreateUser);

        miSelectDifficulty.setText("Select Difficulty");
        meGame.add(miSelectDifficulty);

        miStartGame.setText("Start Game");
        meGame.add(miStartGame);

        jMenuBar1.add(meGame);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelGameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelGameKeyPressed

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                player.x -= 10;
                break;
            case KeyEvent.VK_RIGHT:
                player.x += 10;
                break;
            case KeyEvent.VK_UP:
                player.y -= 10;
                break;
            case KeyEvent.VK_DOWN:
                player.y += 10;
                break;
            default:
                break;
        }
        repaint();

    }//GEN-LAST:event_panelGameKeyPressed

    @Override
    public void paint(Graphics gParent) {
        Graphics2D g = (Graphics2D) panelGame.getGraphics();
        g.clearRect(0, 0, panelGame.getWidth(), panelGame.getHeight());
        g.fillRect(obstacle.x, obstacle.y, 10, 10);
        obstacle.y += 1;
        g.setColor(Color.red);
        g.fillRect(player.x, player.y, 10, 10);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu meGame;
    private javax.swing.JMenuItem miCreateUser;
    private javax.swing.JMenuItem miSelectDifficulty;
    private javax.swing.JMenuItem miStartGame;
    private javax.swing.JPanel panelGame;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                Thread.sleep(100);
                repaint();
            } catch (InterruptedException ex) {
                Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }
}
